# Generated by Django 5.0.2 on 2024-02-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled')], default='1', max_length=2),
        ),
    ]
